version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: AminiVan12!
      MYSQL_DATABASE: MyNotesServer
    ports:
      - "3309:3306"
    volumes:
      - $HOME/Desktop/MySQL-Snippets/school.sql:/school.sql